[versions]
kotlin = "2.3.10"
kover = "0.8.3"
ktlint = "14.0.1"
dokka = "2.1.0"
licenser = "1.2.0"
githubRelease = "2.5.2"
sonarqube = "5.1.0.4882"
vanniktechPublish = "0.36.0"
zalando-problem = "0.27.1"
checker-qual = "3.49.1"

slf4j = "2.0.4"
kotlinCoroutines = "1.10.2"
kotlinIO = "0.8.2"
uriTemplate = "1.3.0"
jackson = "2.19.4"
okhttp = "4.12.0"
junit = "5.10.2"
junitPlatform = "1.10.2"
strikt = "0.35.1"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-jdk9 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk9", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
strikt-jvm = { module = "io.strikt:strikt-jvm", version.ref = "strikt" }
strikt-jackson = { module = "io.strikt:strikt-jackson", version.ref = "strikt"  }

kotlinx-io-core = { module="org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinIO" }
kotlinx-io-bytestring = { module="org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinIO" }
kotlinx-io-okio = { module="org.jetbrains.kotlinx:kotlinx-io-okio", version.ref = "kotlinIO" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

zalando-problem = { module = "org.zalando:problem", version.ref = "zalando-problem" }
zalando-jacksonProblem = { module = "org.zalando:jackson-datatype-problem", version.ref = "zalando-problem" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker-qual" }

uri-template = { module = "com.github.hal4j:uritemplate", version.ref = "uriTemplate" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-cbor = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-javadoc-gradle-plugin = { module = "org.jetbrains.dokka-javadoc:org.jetbrains.dokka-javadoc.gradle.plugin", version.ref = "dokka" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
licenser-gradle-plugin = { module = "net.minecraftforge.licenser:net.minecraftforge.licenser.gradle.plugin", version.ref = "licenser" }
vanniktech-maven-publish-gradle-plugin = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "vanniktechPublish" }

[bundles]
kotlin-io = ["kotlinx-io-core", "kotlinx-io-bytestring"]
jackson = ["jackson-databind", "jackson-module-kotlin", "jackson-dataformat-cbor"]
junit = ["junit-jupiter-api", "junit-jupiter-engine", "junit-jupiter-params"]
strikt = ["strikt-jvm", "strikt-jackson"]

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
github-release = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
